[gcp_service_account]
type = "service_account"
project_id = "digital-badge-466719"
private_key_id = "bcc97bb66e75b72b28ff748a51765ca115474a1c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC0rGUyLc3953Aw
mlj8LjPcW1QzLO7Bq6SOCPYesZg6E1OXvvEYAPuLgDYYImEQVEBZvzgCq/X4AZxl
848V6nutYNwdHvrtxeRzTH1Sdf9t5ALar7mHVHdOrKL5EBHwTZ54hlkhflJNk4i7
XMf2Wh/irh4q0Q+gwVf8zLYUZVeu/RueMXmsh7l2IWQ/YKdecJXWWa2aEmWf+JvT
tSroimwI/yLMeX3DMS9F2JzWFol+bMrogY/mSVyawdGVyTS4B6UsRXbAl3s/T2l3
T9RdHhAK6yFiTn+0dQvSx2afX1gydA9/5PpqJtMLK0srD53vY43vGorUHrc1mIG4
2cUn0K+FAgMBAAECggEAFi/VfYQCd9uj+1P4+X7y/2x3upEaAM6DNq4DC2Hjv73/
1fKsyLXWLhtgiTYvlUHDZUIGLs3PNtV7z0lJmPdimLf8T9cuGWTj2QTbnvS+mVAW
yaQqtGO7Av5QRSWkDk5513MoHuTUVpJ3iAqsw6PtpnibW8awlJ0poPHCql6HlgVq
JVcJZWwBeJgXPwcQnTc6VyEvf2U/nEtMX4DPUrB45YKQ8aHsCG8vPDPO9qBun4ww
76wjCi3m6mqRJUPAqO4VmPyauJnlMnbj1bUoBpkJpHemnxO26nlFABgmAaDJ+rF2
JkUcImVVQc+w8xV68ncgY+NNYLlcSJvEPo2I9K3aAQKBgQDkFJm2rcezshsgDB1x
hYqGWYMQiGpstciac5e3t2KWhUYPOdH32Bx2CAhuOgqMb9M8tpOitcxtOE6fcfVv
BRrI+ID2EvuIpqZaIoBQozicjPPUIlmLvVWz7KT5uQ8xvHWvX3zgohXPSFC9GuPQ
1BTp5f2xQ/WvZ7m5Th+Jsbi+KQKBgQDKyjD+p4xmUbdigrY+XPmrRwhHjClGvAkM
vNU3iLNs/YFlYTIH4Q3dA7JO2aYIQSaEqBkZxpjkbp4WqYY5VdP3+CacgS8aaPGj
ivtbJUAJM55kcoXP40SDXthvIicQuE08QSFH21wYZpO5PD6x4TiqTTGtKB7yXaVf
PubH3CzZ/QKBgDaKlpeQxwi5trLbMs9K1+14ylbRyGFmtyn4KnfMas8D39UURpm2
HFg9Y4a4an1a4HDMWFG4l8ImjOakIcUCu30DsBMoRu5Oq8kyJu0hmxAUxNodvLwl
8rCsDmeJUZDbOGlPtFUjbYO8D1Kpc4EktjuYvCn/zmi7rTYa8H/E+CDBAoGBAIfq
jn4PpD1r5aKkAyu3Oyt992Gk4oFjRBmCctG+0KtrGY/uXg8D2zvX32mT3QFJUVy2
IeSxxAXO0ixUQP8qtGBNtOtOdliYH+TCIQgM5meEblPaoi8cnu4B4sRRuqctL68D
5B96ObatAbO0Wjz0u/sAtBvfeSZud4ln6lvoCTOtAoGAV/pb2Vy+CW2qoutWeS6G
GoyD63Joz0oTiOn78TpWzoJD8M/HJeAWh5cwV2us1psZgEirkHjs8fj1f9AKi9xr
MeV78OaV3zroQqhbE35y6y6Q6JG1naeEjtiSwOLhrWTVGmbWC2uoq5a8YFpNKjN2
Y9vpIavAYOFbGFcLC0eu8XU=
-----END PRIVATE KEY-----"""
client_email = "streamlit-digital-badge@digital-badge-466719.iam.gserviceaccount.com"
client_id = "101719476148200958842"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-digital-badge@digital-badge-466719.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
